spring:
  datasource:
    hikari:
      data-source-properties:
        useConfigs: maxPerformance
        rewriteBatchedInserts: true
    platform: postgres
#    url: jdbc:postgresql://localhost:5432/socialnet
#    username: postgres
#    password: test
    url: jdbc:postgresql://81.177.6.228:5432/socialnet
    username: snuser
    password: snpassword

  security:
    user:
      name: admin
      password: admin